version: "2.3"
services:
  couchdb:
    image: apache/couchdb:2.1
    volumes:
      - couchdb-data:/opt/couchdb/data
    networks:
      - intranet

  redis:
    image: redis:alpine
    networks:
      - intranet

  cozy:
    image: moritzheiber/cozy-stack
    links:
      - couchdb:couchdb
      - redis:redis
    ports:
      - "8080:8089"
    volumes:
      - cozy-storage:/cozy/storage
    networks:
      - docker_network
      - intranet
    depends_on:
      - couchdb
      - redis

volumes:
  couchdb-data:
  cozy-storage:
networks:
  docker_network:
    driver: bridge
  intranet:
    internal: true
